### ISSUE TITLE
Don't hardcode and commit api keys to public repos

### ISSUE THREAD

**Issue by justin-gerhardt** [alegemaate/automated-watering#1]
https://github.com/alegemaate/automated-watering/blob/59090f5742380356de300c44dbdc583f0a95b879/apws.py#L18

**Comment by alegemaate** [comment]
Thanks! Fixed

**Comment by justin-gerhardt** [comment]
This issue still references the commit that was removed from history. If you check the link you can still see the token. You are going to have to delete the issue or initial message.
